### ISSUE TITLE
Gist link for migrate from existing project

### ISSUE THREAD

**Issue by italomlp** [emin93/react-native-template-typescript#35]
I have a project with React-Native, that uses Javascript and PropTypes. So, I saw the benefits in the use of Typescript, and migrate to this. In the web, there are many tutorials, most of them a little old, and the recents are not complete or acceptable. So, I found this template, but don't want to start a new project and import the code. So, based in it (and in its setup.js), I did all by myself, and make a Gist for this migration.

My suggestion is, if you agree and think that it's helpful, add it to the links section of this repo.

The link for it is
https://gist.github.com/italomlp/4d16bf0f19d09f9fae48d272f9e6306e

**Comment by emin93** [comment]
Hey @italomlp,

Thank you for creating the issue and the time you took to create a Gist on how to migrate an existing project to TypeScript. As you already found out, this is no rocket science and pretty easy since the introduction of Babel 7.

If you wish to add your Gist to the links section, feel free to create a pull request 😃
